name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
          pip install pytest
      - name: Run unit tests
        run: |
          . .venv/bin/activate
          pytest -q
      - name: Smoke train (2 epochs)
        run: |
          . .venv/bin/activate
          python model.py --epochs 2
